### ISSUE TITLE
LESS compiling

### ISSUE THREAD

**Issue by KeijoH** [trongthanh/geany-for-front-end-dev#1]
One of the things that Front-End designers will sometimes face is LESS -> CSS compiling and I found this page most usefull for me and works great on Geany and Fedora Linux for automatically compiling when saving LESS file.

http://stackoverflow.com/questions/13671969/how-to-automatically-compile-less-into-css-on-the-server

I use the Ian Marcinkowski modified script as that handles also editing LESS import files at the same time. Geany Terminal is very usefull for this. Maybe this (or something better) could be added to Geany for front-end developer guide?

**Comment by trongthanh** [comment]
Hi there,

I'm totally for any enhancement to the front end dev workflow on Geany. I don't personally use LESS so can you help write up a wiki page regarding this. I will add it to the Wiki home page and the README.md for others' references.

**Comment by trongthanh** [comment]
After few emails, the wiki is up here: https://github.com/trongthanh/geany-for-front-end-dev/wiki/Using-LESS-CSS-pre-processor-with-Geany
